#define REMOTE_A        0
#define REMOTE_B        1
#define REMOTE_1        2
#define REMOTE_2        3
#define REMOTE_MINUS    4
#define REMOTE_PLUS     5
#define REMOTE_HOME     6
#define NUNCHUCK_Z      7
#define NUNCHUCK_C      8
#define CLASSIC_A       9
#define CLASSIC_B       10
#define CLASSIC_X       11
#define CLASSIC_Y       12
#define CLASSIC_L       13
#define CLASSIC_R       14
#define CLASSIC_ZL      15
#define CLASSIC_ZR      16
#define CLASSIC_MINUS   17
#define CLASSIC_PLUS    18
#define CLASSIC_HOME    19
